name: icon-automation
on:
  push:
    branches:
    - master
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # 更新到最新版本

    - uses: actions/setup-node@v4  # 更新到最新版本
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    # 添加 npm 配置步骤
    - name: Configure npm
      run: |
        npm config set strict-ssl false
        npm config set registry http://registry.npmjs.org/

    # 修改所有 yarn 命令
    - run: yarn install --network-timeout 100000 --insecure
    - name: Figma Action
      uses: primer/figma-action@v1.0.0-alpha.2
      with:
        args: "format=svg outputDir=./src/"
      env:
        FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

    - run: yarn generate --network-timeout 100000
    - run: yarn build:bundle --network-timeout 100000

    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
    - run: yarn publish --network-timeout 100000
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: yarn build --network-timeout 100000

    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
