name: icon-automation
on:
  push:
    branches:
    - master
    paths:
      - package.json

jobs:
  icon_automation:
    name: figma icon automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 更新系统证书
    - name: Update CA certificates
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates
        sudo update-ca-certificates

    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    # 配置和更新 yarn
    - name: Configure yarn
      run: |
        npm install -g yarn
        yarn config set registry https://registry.npmjs.org
        yarn config set network-timeout 300000
        yarn config set strict-ssl false
    
    - run: echo "FIGMA_TOKEN ${{secrets.FIGMA_TOKEN}} FIGMA_FILE_URL ${{secrets.FIGMA_FILE_URL}} NPM_AUTH_TOKEN ${{secrets.NPM_AUTH_TOKEN}}"

    - run: yarn install --network-timeout 300000 --no-lockfile
    - name: Figma Action
      uses: primer/figma-action@v1.0.0-alpha.2
      with:
        args: "format=svg outputDir=./src/"
      env:
        FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

    - run: yarn generate
    - run: yarn build:bundle

    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - run: yarn build

    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
